### ISSUE TITLE
Return the Quantity object at Metrics.stopTimer

### ISSUE THREAD

**Issue by jkhlam** [ArpNetworking/metrics-client-java#38]
When I stop the timer, I want to know the elapsed time (i.e. Quantity) of the timer.

Use case: If the elapsed time is longer than a threshold, I want to be able to log additional warnings, or perform extra business logic.

Currently, I have to keep track my own start/stop time and use Metrics.setTimer instead of Metrics.startTImer/stopTimer. It will be convenient if the metrics can provide the elapsed time when the timer i stopped since the Metrics timer is already timing the duration.

**Comment by vjkoskela** [comment]
Thanks for the feedback!

As I see it, we have two options here that could make this easier.

1) Return a Quantity instance from the stopTimer method on Metrics. This will be a non-backwards compatible interface change for anyone extending our library; however, it will be backwards compatible for consumers.

2) Currently TsdTimer implements Timer and Quantity while Timer only implements AutoCloseable. Instead, we could have Timer extend AutoCloseable and Quantity. This allows a timer instance to be queried for its value and unit (treated as a quantity). This will be backwards compatible. Further, we could then implement option 1 above by return the timer instance that was stopped in stopTimer on Metrics thereby avoiding construction of an unnecessary Quantity instance.

@BrandonArp what are your thoughts?

**Comment by BrandonArp** [comment]
I vote for 2.  It's not backwards compatible, however.  It has the same problem as 1 where an extender of the library would now also have to implement Quantity.

**Comment by vjkoskela** [comment]
Well #2 as written is backwards compatible when TsdTimer extends both Timer and Quantity. But I'm thinking you mean to have Timer extend Quantity which is not backwards compatible. In fact, I'm a little more concerned about that (versus having TsdTimer extend Quantity). I'll try and play around with it tonight and get you either some more feedback or a poc.

**Comment by vjkoskela** [comment]
@jkhlam I've taken a look at this and before I dive into what I'm proposing, I do want to caution you against adding conditional logic based on data collected by the metrics library. Our view on this library is that it is much like a logging library and should be transparent to your application's operation. For example, this lead us to build an exception-neutral implementation where methods log error conditions (e.g. timer already closed) instead of throwing exceptions (similar to how slf4j/logback/log4j behave).

In your use case I would suggest using `createTimer` instead of `startTimer` and `stopTimer` to return a `Timer` object. You can then use the `Timer` object's value after `close` (or `stop`) to determine whether you want to log something else (once my change is merged/released). Again, adding business logic (as opposed to logging) gives me some pause. If you are working in a straight-forward single threaded model it's probably nothing to worry about, but in a concurrent or asynchronous model it can be more complicated (e.g. we won't throw an exception if you evaluate the timer value before its closed; so your business logic may make a bad decision).

The reason I am not returning a `Timer` (or more precisely a `Quantity`) from the `stopTimer` with this change is because it would have to be either `@Nullable` or `Optional` because if the `Metrics` instance is closed or the timer name has not been started then I can't throw an exception (see explanation as above). I considered returning an `Optional`, and went so far as to code it up for timers and counters, but the semantics started to get awkward and were no longer symmetrical with `createTimer`. 

Two longer-term notes here:

1) We've had other requests to expose a `StopWatch` (e.g. #10) which could be used to separate the semantics of measurement from recording allowing you to build your logic using our constructs. The reason we have not done this yet is that there are already many stop watch implementations (e.g. Guava: https://google.github.io/guava/releases/18.0/api/docs/com/google/common/base/Stopwatch.html) that do a great job; and if you're going to instantiate something and then call `setTimer` it doesn't really matter if it's our stop watch or someone else's. Effectively, this sounds like what you are doing already.

2) We've also considered building a variant of the interfaces that does throw exceptions. This would help with debugging race conditions in concurrent systems and also allow some of the state to be hardened so clients so inclined could depend on the results as you do (or else deal with the exceptions). This is a much larger undertaking, and thus far we have not been convinced of its value (versus cost and given resources -- or lack thereof). 

I would love your feedback on both those issues and anything else you think could be improved here.

**Comment by vjkoskela** [comment]
@jkhlam please let us know if this addresses your issue and we can release the next version with change #39

**Comment by jkhlam** [comment]
@vjkoskela  I apologize for the much delayed response.  The changes work great.  Thank you very much!
